name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: yarn install
      - run: yarn typecheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: yarn install
      - run: yarn vite:build
      - run: yarn utility:build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: yarn install
      - run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: yarn install
      - run: yarn lint

