name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-test-lint-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: yarn install
      - run: yarn build
#      - run: yarn test
      - run: yarn lint
      - run: yarn typecheck
